[Feature]: Reformat resize config
open-mmlab/mmcv pull request #1826
Opened 2022-03-23 08:42 UTC by YuanLiuuuuuu

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

**Before PR**:

- [ ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects, like MMDet or MMCls.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-03-23 08:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=1826) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=1826) before we can accept your contribution.<br/>**6** out of **7** committers have signed the CLA.<br/><br/>:white_check_mark: mzr1996<br/>:white_check_mark: ly015<br/>:white_check_mark: ZwwWayne<br/>:white_check_mark: Harold-lkk<br/>:white_check_mark: plyfager<br/>:white_check_mark: YuanLiuuuuuu<br/>:x: Your<br/><hr/>**Your** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmcv?pullRequest=1826) it.</sub>

2022-03-24 11:18 UTC, mzr1996 requested changes

2022-03-24 11:18 UTC, mzr1996 commented on mmcv/transforms/processing.py
> +    def _random_scale(self) -> None:
return Tuple

2022-03-24 11:18 UTC, mzr1996 commented on mmcv/transforms/processing.py
> +            dict: One new key ``scale`` is added into ``results``,
The return type is not dict now.

2022-03-24 11:49 UTC, YuanLiuuuuuu commented on mmcv/transforms/processing.py
> +    def _random_scale(self) -> None:
I think it's tuple, instead of Tuple.

2022-03-25 04:33 UTC, mzr1996 approved these changes
Looks good

2022-03-25 07:53 UTC, MeowZheng commented on mmcv/transforms/processing.py
> +        resize_cfg (dict): Config to initialize a ``Resize`` object.
might present default value
a ``Resize`` object -> a ``Resize`` transform?

2022-03-25 07:56 UTC, Harold-lkk commented
LGTM

2022-03-25 07:59 UTC, MeowZheng commented on mmcv/transforms/processing.py
> +      [``scale[0][1]``, ``scale[1][1]``] uniformally.
might mention 'follow xx convention,scale[0][0] is for height? and  scale[1][0] for width?'

2022-03-25 13:02 UTC, MeowZheng approved these changes

2022-03-28 05:36 UTC, Harold-lkk approved these changes

2022-03-28 06:18 UTC, merged